{% set name = "sphinxcontrib-youtube" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eb7871c8af47fd2b5c9727615354b7f95bce554be8be45b9fa8e5bc022f88059

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit
  run:
    - python >={{ python_min }}
    - sphinx >=6.1
    - requests

test:
  imports:
    - sphinxcontrib.youtube
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/sphinx-contrib/youtube
  summary: 'Sphinx "youtube" extension'
  description: |
    This package contains the youtube Sphinx extension.

    The extension defines the directives, “youtube” and “vimeo”, for embedding YouTube and Vimeo videos, respectively.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENCE
  doc_url: https://sphinxcontrib-youtube.readthedocs.io
  dev_url: https://github.com/sphinx-contrib/youtube

extra:
  recipe-maintainers:
    - moorepants
